//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slv_authApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string login { get; set; }
        public int id { get; set; }
        public string password { get; set; }
        public int type { get; set; }
    
        public virtual User_Type User_Type { get; set; }
    }
}
